//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_details
    {
        public int fileid { get; set; }
        public string filename { get; set; }
        public string fileloc { get; set; }
        public string fileurl { get; set; }
    }
}
